# -*- coding: utf-8 -*-
"""Remeote Working Survey.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZZKGXS__KofSVlZ3orNZuu-pKMPJprj
"""

import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt
import seaborn as sns





from google.colab import files


uploaded = files.upload()

from google.colab import files


uploaded = files.upload()

from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/portfolio project 02/2020_rws.csv'

encoding = 'latin1'

df = pd.read_csv("/content/drive/MyDrive/portfolio project 02/2020_rws.csv",encoding='cp1252')

df.head()

x = list(df.columns)
x[7]

df["Which of the following best describes your household?  "]

import chardet

file_path = '/content/drive/MyDrive/portfolio project 02/2020_rws.csv'

with open('/content/drive/MyDrive/portfolio project 02/2020_rws.csv', 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))

encoding = result['encoding']

df = pd.read_csv('/content/drive/MyDrive/portfolio project 02/2020_rws.csv', encoding=encoding)

df.head()

df = df.drop_duplicates()

missing_data = df.isnull().sum()

summary_stats = df.describe()

categorical_column = 'Which of the following best describes your industry?'
categorical_counts = df[categorical_column].value_counts()

df['What is your gender?'].value_counts()

df['What is your gender?'].value_counts().plot (kind='bar', figsize=(15,7))

x = list(df.columns)
x[60]

df.head()

x = list(df.columns)
x[42]

df = pd.DataFrame(data)

# Identify all columns with the name 'd'
columns_with_choices = [col for col in df.columns if ''From the following, please select the least significant barrier to doing your work remotely - Connectivity (internet connection) ; Feeling left out and/or isolated ; Poor management ; IT equipment (computer, printer, etc.) ; Difficulty collaborating remotely ; Caring responsibilities'' in col]

# Add up values in columns with the name 'd'
df[merged_From the following, please select the least significant barrier to doing your work remotely - Connectivity (internet connection) ; Feeling left out and/or isolated ; Poor management ; IT equipment (computer, printer, etc.) ; Difficulty collaborating remotely ; Caring responsibilities] = df[columns_with_From the following, please select the least significant barrier to doing your work remotely - Connectivity (internet connection) ; Feeling left out and/or isolated ; Poor management ; IT equipment (computer, printer, etc.) ; Difficulty collaborating remotely ; Caring responsibilities].astype(str).agg(';'.join, axis=1)

# Drop the original columns with the name 'd'
#df = df.drop(columns=columns_with_From the following, please select the least significant barrier to doing your work remotely - Connectivity (internet connection) ; Feeling left out and/or isolated ; Poor management ; IT equipment (computer, printer, etc.) ; Difficulty collaborating remotely ; Caring responsibilities)

print(df)

a= print("hello world")

